ASP_Dot_Net_MVC_Aug_2021/Controllers/ItemsController.cs
using ASP_Dot_Net_MVC_Aug_2021.Data.Interfaces;
using ASP_Dot_Net_MVC_Aug_2021.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP_Dot_Net_MVC_Aug_2021.Controllers
{
    public class ItemsController : Controller
    {
        private readonly IItemRepo _repository;

        public ItemsController(IItemRepo repository)
        {
            _repository = repository;
        }

        // GET: ItemsController
        public ActionResult Index()
        {
            return View(_repository.GetAllItems());
        }

        // GET: ItemsController/Details/5
        public ActionResult Details(int id)
        {
            return View(_repository.GetItemById(id));
        }

        // GET: ItemsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ItemsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Item newItem)
        {
            try
            {
                _repository.CreateItem(newItem);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ItemsController/Edit/5
        public ActionResult Edit(int id)
        {
            var itemToEdit = _repository.GetItemById(id);
            return View(itemToEdit);
        }

        // POST: ItemsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Item item)
        {
            try
            {
                _repository.UpdateItem(item);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ItemsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_repository.GetItemById(id));
        }

        // POST: ItemsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                _repository.DeleteItem(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult CarouselDemo()
        {
            return View();
        }
    }
}

ASP_Dot_Net_MVC_Aug_2021/Controllers/OrderController.cs
using ASP_Dot_Net_MVC_Aug_2021.Data;
using ASP_Dot_Net_MVC_Aug_2021.Data.Interfaces;
using ASP_Dot_Net_MVC_Aug_2021.Models;
using ASP_Dot_Net_MVC_Aug_2021.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP_Dot_Net_MVC_Aug_2021.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepo _orderRepo;
        private readonly IProductRepo _productRepo;
        private readonly IOrderProductsRepo _orderProductsRepo;
        private readonly Mapper _mapper = new Mapper();

        public OrderController(IOrderRepo orderRepo, 
            IProductRepo productRepo, IOrderProductsRepo orderProductsRepo)
        {
            _orderRepo = orderRepo;
            _productRepo = productRepo;
            _orderProductsRepo = orderProductsRepo;
        }

        // GET: OrderController
        public ActionResult Index()
        {
            var orders = _orderRepo.GetAllOrders().Select(o => _mapper.Map(o));
            return View(orders);
        }

        // GET: OrderController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: OrderController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OrderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OrderController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: OrderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OrderController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: OrderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        public ActionResult GetProductsByOrderId(int id)
        {
            var orderProduct = _orderProductsRepo.GetAllOrderProducts();
            var products = _productRepo.GetAllProducts()
                .Select(p =>
                    new ProductVM {
                        Id = p.P_Code,
                        Description = p.P_descript,
                        Price = p.P_Price,
                        IsActive =
                        orderProduct
                            .Where(op => op.ProductId == p.P_Code &&
                                op.OrderId == id)
                            .FirstOrDefault() == null ? false : true
                    }
                )
                .ToList();

            SaveProductsInOrderVM pvm = new SaveProductsInOrderVM { 
                Products = products,
                OrderId = id
            };

            return PartialView(pvm);
        }

        public ActionResult SaveProducts(SaveProductsInOrderVM obj)
        {
            _orderProductsRepo.RemoveRange(obj.OrderId);

            var rangeToAdd = obj.Products
                .Where(p => p.IsActive)
                .Select(op => new OrderProducts
                {
                    OrderId = obj.OrderId,
                    ProductId = op.Id
                });

            _orderProductsRepo.AddRange(rangeToAdd);
            _orderProductsRepo.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

ASP_Dot_Net_MVC_Aug_2021/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASP_Dot_Net_MVC_Aug_2021.Data.Interfaces;
using ASP_Dot_Net_MVC_Aug_2021.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using ASP_Dot_Net_MVC_Aug_2021.Data;
using ASP_Dot_Net_MVC_Aug_2021.ModelsDto;

namespace ASP_Dot_Net_MVC_Aug_2021.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepo _productRepo;
        private readonly IVendorRepo _vendorRepo;
        private readonly Mapper _mapper = new Mapper();

        public ProductController(IProductRepo prodRepo, 
            IVendorRepo vendorRepo)
        {
            _productRepo = prodRepo;
            _vendorRepo = vendorRepo;
        }
        public IActionResult Index()
        {
            var vendors = _vendorRepo.GetAllVendors();
            var list = _productRepo.GetAllProducts()
                .Select(p => {
                    p.Vendor = vendors
                                .Where(v => v.V_code == p.V_code)
                                .FirstOrDefault() ?? new Vendor { 
                                    V_name = "no vendor"
                                };
                    return p;
                })
                .Select(p => _mapper.Map(p))
                .ToList();
            
            
            return View(list);
        }

        public IEnumerable<string> GetProductsByVendorId(int? id)
        {
            var res = _productRepo.GetAllProducts()
                .Where(p => p.V_code == id)
                .Select(p => p.P_descript + "\t$" + p.P_Price + "<br>");

            if(res == null || res.Count() == 0)
            {
                return new List<string> { "No Product found "};
            }

            return res;
        }

        public ActionResult Create()
        {
            var list = _vendorRepo.GetAllVendors()
                .Select(v => _mapper.Map(v))
                .ToList();

            list.Add(new VendorDto() { V_code = -1, V_name = " - Select Vendor" });
            list.Sort((foo1, foo2) => foo1.V_code.CompareTo(foo2.V_code));
            //list.Reverse();
            ViewBag.Vendors = 
                new SelectList(list,
                "V_code", "V_name");

            return View();
        }

        [HttpPost]
        public ActionResult Create(ProductDto product)
        {
            if (ModelState.IsValid)
            {
                _productRepo.CreateProduct(_mapper.Map(product));
                _productRepo.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        public ActionResult Edit(string id)
        {
            var list = _vendorRepo.GetAllVendors()
                .Select(v => _mapper.Map(v))
                .ToList();
            ViewBag.Vendors =
                new SelectList(list,
                "V_code", "V_name");

            var prod = _mapper.Map( _productRepo.GetProductById(id) );

            return View(prod);
        }

        [HttpPost]
        [Route("Product/Edit")]
        public ActionResult Edit(ProductDto input)
        {
            _productRepo.UpdateProduct( _mapper.Map( input ) );
            _productRepo.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

ASP_Dot_Net_MVC_Aug_2021/Controllers/VendorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASP_Dot_Net_MVC_Aug_2021.Data.Interfaces;
using ASP_Dot_Net_MVC_Aug_2021.Models;
using ASP_Dot_Net_MVC_Aug_2021.Data;
using ASP_Dot_Net_MVC_Aug_2021.ModelsDto;

namespace ASP_Dot_Net_MVC_Aug_2021.Controllers
{
    public class VendorController : Controller
    {
        private readonly IVendorRepo _vendorRepo;
        private readonly Mapper _mapper = new Mapper();

        public VendorController(IVendorRepo vendorRepo)
        {
            _vendorRepo = vendorRepo;
        }
        public IActionResult Index()
        {
            var list = _vendorRepo.GetAllVendors()
                .Select(v => _mapper.Map(v))
                .ToList();
            return View(list);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(VendorDto input)
        {
            _vendorRepo.CreateVendor(_mapper.Map(input));
            _vendorRepo.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Edit(int id)
        {
            var v =  _mapper.Map(_vendorRepo.GetVendorById(id));
            return View(v);
        }

        [HttpPost]
        public ActionResult Edit(VendorDto vendor)
        {
            _vendorRepo.UpdateVendor(_mapper.Map(vendor)); 
            _vendorRepo.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

ASP_Dot_Net_MVC_Aug_2021/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP_Dot_Net_MVC_Aug_2021</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP_Dot_Net_MVC_Aug_2021</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Index">Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="CarouselDemo">Candy machine</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vendor" asp-action="Index">Vendors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ASP_Dot_Net_MVC_Aug_2021 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>